### ISSUE TITLE
Role don't upgrade to 2.1.0p2

### ISSUE THREAD

**Issue by fabriceverkor** [kso512/checkmk_server#1]
I have an already installed server thanks former role version, and thus checkmk server  2.0.0p22.
I just upgraded role to last version.
Even if defaults/main.yml contains checkmk_server_version: "2.1.0p2", rolei still trying to install 2.0.0p22 but fails with following error :
fatal: [10.15.100.12]: FAILED! => {
    "changed": true,
    "checksum_dest": null,
    "checksum_src": "4d3a3cfbdc9f0d0f3b04eeb02d88d7f494cba620",
    "dest": "/opt/check-mk-raw-2.0.0p22_0.bullseye_amd64.deb",
    "elapsed": 9,
    "invocation": {
        "module_args": {
            "attributes": null,
            "backup": false,
            "checksum": "sha256:4db32d23523053ed028cf13d242b1972a406c9deeb6d80e277c6180200b2e263",
            "client_cert": null,
            "client_key": null,
            "dest": "/opt/check-mk-raw-2.0.0p22_0.bullseye_amd64.deb",
            "force": false,
            "force_basic_auth": false,
            "group": null,
            "headers": null,
            "http_agent": "ansible-httpget",
            "mode": "0644",
            "owner": null,
            "selevel": null,
            "serole": null,
            "setype": null,
            "seuser": null,
            "sha256sum": "",
            "timeout": 10,
            "tmp_dest": null,
            "unsafe_writes": false,
            "url": "https://download.checkmk.com/checkmk/2.0.0p22/check-mk-raw-2.0.0p22_0.bullseye_amd64.deb",
            "url_password": null,
            "url_username": null,
            "use_proxy": true,
            "validate_certs": true
        }
    },
    "msg": "The checksum for /opt/check-mk-raw-2.0.0p22_0.bullseye_amd64.deb did not match 4db32d23523053ed028cf13d242b1972a406c9deeb6d80e277c6180200b2e263; it was 6cdeaa49f61edc07675b420a6c84169c93215db9c1615c3ea44995b134131aac.",
    "src": "/home/vking/.ansible/tmp/ansible-tmp-1654839717.4765503-2060689-251134850479990/tmpms_jozcy",
    "url": "https://download.checkmk.com/checkmk/2.0.0p22/check-mk-raw-2.0.0p22_0.bullseye_amd64.deb"
}

**Comment by fabriceverkor** [comment]
My bad : somewhere in ansible was defined checkmk_server_version with '2.0.0p22' value. Please note that OMS sites need to be updated to new version with 'omd update' command

**Comment by kso512** [comment]
Hi fabriceverkor!

Thanks for opening this and good find on the external declaration of the version variable.

I recently added some explanation to the documentation on how and why this role doesn't perform the upgrades: https://github.com/kso512/checkmk_server#upkeep-updates-and-out-dated-versions

Thank you for using this role!
